site_name: Szyw's World
site_url: https://blog.szyw.org
site_description: Self-hosting shenanigans fueled by chocolate and coffee.
#repo_url: https://github.com/Zszywany/website
#repo_name: Zszywany/website
plugins:
  - blog
  # Enabling 'social' plugin requires to 'pip install mkdocs-material[imaging]' to build the site.
  - social
theme:
  name: material
  # If I use overrides for footer I have to craft the full HTML by myself. Not feasible now.
  #custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
    accent: deep orange
  features:
    - navigation.indexes
    - navigation.instant # skip reloading the header and logo
  #icon:
    #logo: material/book-open-page-variant
  logo: images/logo.png
  favicon: images/favicon.png
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About me: about.md
# Full copyright notice is too long for mobile screen. Hybrid it is.
copyright: Copyright &copy; 2025 Zszywany. This work is licensed under CC BY-NC 4.0.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Zszywany
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/Zszywany
