site_name: Szyw's World
site_url: https://blog.szyw.org
plugins:
  - blog
theme:
  name: material
  #custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
    accent: deep orange
  features:
    - navigation.indexes
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About me: about.md
#copyright: Szyw's World  © 2025 by Zszywany is licensed under CC BY-NC 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0/
#copyright: This work is licensed under CC BY-NC 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0/
copyright: Szyw's World  © 2025 by Zszywany is licensed under CC BY-NC 4.0.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Zszywany
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/Zszywany
